global:
  name: consul
  datacenter: dc1
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
  replicas: 1
  default: true
controller:
  enabled: true
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: NodePort
        ports:
        - port: 8080
          nodePort: 32080
prometheus:
  enabled: true
grafana:
  enabled: true